-- MySQL Script generated by MySQL Workbench
-- Fri Mar 12 15:31:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cidade_das_carnes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cidade_das_carnes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cidade_das_carnes` DEFAULT CHARACTER SET utf8 ;
USE `db_cidade_das_carnes` ;

-- -----------------------------------------------------
-- Table `db_cidade_das_carnes`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cidade_das_carnes`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `tipo_carne` VARCHAR(45) NOT NULL,
  `qualidade` VARCHAR(45) NOT NULL,
  `produtor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cidade_das_carnes`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cidade_das_carnes`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `peso` DECIMAL(3,2) NULL DEFAULT 1,
  `preco` DECIMAL(4,2) NOT NULL,
  `id_cat_produto` INT NOT NULL,
  PRIMARY KEY (`id_produto`, `id_cat_produto`),
  UNIQUE INDEX `id_produto_UNIQUE` (`id_produto` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_categoria_idx` (`id_cat_produto` ASC) VISIBLE,
  CONSTRAINT `id_cat_produto`
    FOREIGN KEY (`id_cat_produto`)
    REFERENCES `db_cidade_das_carnes`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tb_categoria(tipo_carne, qualidade, produtor) VALUES
("Bovina","Premium", "JBS"),
("Suina", "Padrão", "Aurora"),
("Bovina", "Padrão", "Friboi");

INSERT INTO tb_produto(nome, preco, id_cat_produto) VALUES
("Linguiça", 25.99, 2),
("Bife", 48.99, 3),
("Costela", 47.99, 1),
("Bisteca", 18.99, 2);

-- selects 

SELECT * FROM tb_produto WHERE preco > 50;
SELECT * FROM tb_produto WHERE preco >=3 AND preco<=60;
SELECT * FROM tb_produto WHERE nome LIKE "%c%";

-- inner join

SELECT * FROM tb_produto 
INNER JOIN tb_categoria ON tb_produto.id_cat_produto = tb_categoria.id_categoria
WHERE qualidade = "Premium";