-- MySQL Script generated by MySQL Workbench
-- Fri Mar 12 13:17:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pizzaria_legal` DEFAULT CHARACTER SET utf8 ;
USE `db_pizzaria_legal` ;

-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `salgada` BOOLEAN NOT NULL,
  `vegetariana` BOOLEAN NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC) VISIBLE)
ENGINE = InnoDB;
ALTER TABLE tb_categoria ADD COLUMN massafina BOOLEAN NOT NULL;

-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_pizza` (
  `id_pizza` INT NOT NULL AUTO_INCREMENT,
  `nome_pizza` VARCHAR(45) NOT NULL,
  `tamanho_pizza` VARCHAR(45) NOT NULL DEFAULT 'Grande',
  `preco_pizza` FLOAT NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_pizza`),
  UNIQUE INDEX `id_pizza_UNIQUE` (`id_pizza` ASC) VISIBLE,
  INDEX `id_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `id_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `db_pizzaria_legal`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tb_categoria(salgada,vegetariana,massafina) VALUES
(TRUE,FALSE,TRUE),
(TRUE,TRUE,TRUE),
(FALSE,TRUE,FALSE),
(FALSE,FALSE,FALSE),
(FALSE,FALSE,TRUE);

INSERT INTO tb_pizza(nome_pizza, tamanho_pizza, preco_pizza, id_categoria) VALUES
("Calabresa", "Grande", 42.90, 1),
("Mussarela", "Grande", 42.90, 1),
("Chocolate", "Pequena", 45.90, 4),
("Rúcula", "Grande", 35.90, 2),
("Premium Catupiry", "Grande", 65.90, 1),
("Escarola", "Pequena",22.90,2),
("Bacon", "Pequena", 36.90, 1),
("Banana", "Pequena", 30.90, 3);

-- selects 

SELECT * FROM tb_pizza WHERE preco_pizza > 45;
SELECT * FROM tb_pizza WHERE preco_pizza <=60 AND preco_pizza >=29;
SELECT * FROM tb_pizza WHERE nome_pizza LIKE "%c%";

-- todas pizzas vegetarianas doces

SELECT tb_pizza.nome_pizza, tb_pizza.id_categoria FROM tb_pizza
INNER JOIN tb_categoria ON tb_categoria.id_categoria = tb_pizza.id_categoria
WHERE tb_pizza.id_categoria = 3;